/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TweetMinerJFrame.java
 *
 * Created on 02/11/2010, 20:47:32
 */

package tesis.util;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import tesis.subjectivityClassification.classifiers.SubjectivityClassifier;
import tesis.subjectivityClassification.exceptions.PropertyKeyNotFoundException;
import twitter4j.Query;
import twitter4j.QueryResult;
import twitter4j.Tweet;
import twitter4j.TwitterException;
import twitter4j.TwitterFactory;

/**
 *
 * @author César García Pécora
 */
public class PolarityTweetMinerJFrame extends javax.swing.JFrame {
    SubjectivityClassifier subjectivityClassifier;

    /** Creates new form TweetMinerJFrame */
    public PolarityTweetMinerJFrame() {
        initComponents();
        subjectivityClassifier = new SubjectivityClassifier();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        jList1.setModel(new DefaultListModel());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Polarity Algorithm File Generator");

        jTextField1.setText("Search");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jList1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jButton2.setText("Pos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField2.setText("Max");

        jButton3.setText("Neg");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 775, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        search();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            appendToFile(Config.getPosMinedTweetsFilePath(),jList1.getSelectedValue().toString());
        } catch (PropertyKeyNotFoundException ex) {
            Logger.getLogger(PolarityTweetMinerJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PolarityTweetMinerJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            appendToFile(Config.getNegMinedTweetsFilePath(),jList1.getSelectedValue().toString());
        } catch (PropertyKeyNotFoundException ex) {
            Logger.getLogger(PolarityTweetMinerJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PolarityTweetMinerJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jList1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_1){
            try {
                appendToFile(Config.getPosMinedTweetsFilePath(),jList1.getSelectedValue().toString());
            } catch (PropertyKeyNotFoundException ex) {
                Logger.getLogger(PolarityTweetMinerJFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(PolarityTweetMinerJFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
            if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_2){
                try {
                    appendToFile(Config.getNegMinedTweetsFilePath(),jList1.getSelectedValue().toString());
                } catch (PropertyKeyNotFoundException ex) {
                    Logger.getLogger(PolarityTweetMinerJFrame.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(PolarityTweetMinerJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    }//GEN-LAST:event_jList1KeyPressed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            search();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    public void search(){
        DefaultListModel listModel = new DefaultListModel();
        jList1.setModel(listModel);
        String searchTerm = jTextField1.getText();
        int maxResult;
        String sentence;
        try{
            maxResult = Integer.parseInt(jTextField2.getText());
            if (!searchTerm.isEmpty()){
                if (maxResult > 0){                    
                    twitter4j.Twitter twitter = new TwitterFactory().getInstance();
                    Query query = new Query(searchTerm);
                    query.setLang("en");
                    int tweetsWanted = Integer.parseInt(jTextField2.getText());
                    int pages = tweetsWanted / 100;
                    if (pages == 0)
                        pages = 1;
                    query.setRpp(100);
                    for (int i=1; i<=pages; i++){
                        query.setPage(i);
                        QueryResult result = twitter.search(query);
                        for (Tweet status : result.getTweets()) {
                            if (subjectivityClassifier.isSubjective(status.getText())){
                                sentence = status.getText();
                                listModel.addElement(sentence);
                            }
                        }
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null, "MaxResult should be more than Zero", "Error", JOptionPane.INFORMATION_MESSAGE);
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "Please, fill the Search field", "Error", JOptionPane.INFORMATION_MESSAGE);                
            }
        } catch (TwitterException ex) {
            JOptionPane.showMessageDialog(null, "Twitter API Error", "Error", JOptionPane.INFORMATION_MESSAGE);
        }catch(NumberFormatException exception){
            JOptionPane.showMessageDialog(null, "Invalid Number Format of Max Search", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public void appendToFile (String filePath, String text) {

      BufferedWriter bw = null;

      try {
         bw = new BufferedWriter(new FileWriter(filePath, true));
         text = text.toLowerCase();
         text = text.replace(jTextField1.getText().toLowerCase(),"");
	 bw.write(text);
	 bw.newLine();
	 bw.flush();
      } catch (IOException ioe) {
	 ioe.printStackTrace();
      } finally {
	 if (bw != null) try {
	    bw.close();
	 } catch (IOException ioe2) {	    
	 }
      }
   }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    } catch (ClassNotFoundException e) {
                        e.printStackTrace();
                    } catch (InstantiationException e) {
                        e.printStackTrace();
                    } catch (IllegalAccessException e) {
                        e.printStackTrace();
                    } catch (UnsupportedLookAndFeelException e) {
                        e.printStackTrace();
                    }
                new PolarityTweetMinerJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
